### ISSUE TITLE
Wrong folder reference generated with `yo jasmine`

### ISSUE THREAD

**Issue by jayqui** [yeoman/generator-jasmine#15]
Following [these instructions](http://techportal.inviqa.com/2014/10/28/testing-javascript-get-started-with-jasmine/), I used Yeoman to install Jasmine with `yo jasmine`.  The problem: `tests/index.html` was requiring files in a non-existent directory: `/bower_components/jasmine/`, whereas the proper directory name is `/bower_components/jasmine-core`.  

This should be an easy fix, and I'm happy to try making a pull request sometime soon if someone else doesn't get to it first.

**Comment by SBoudrias** [comment]
@jayqui Pr welcomed :)

I think jasmine change the structure of their project in a release and it just haven't been copied over here.

**Comment by jayqui** [comment]
@SBoudrias Clicking around a little more, it looks like there's been a PR ready to be merged the whole time: https://github.com/yeoman/generator-jasmine/pull/14 .  I'm unsure who has merge permissions.

**Comment by SBoudrias** [comment]
Hum, merged!

**Comment by SBoudrias** [comment]
As you can see, this generator is not actively maintained anymore. We're looking for new maintainers if you're interested.
